name: Spring Boot CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build, Test & Scan
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # 3. Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Build project
      - name: Build with Maven
        run: mvn clean package --batch-mode

      # 5. Run tests
      - name: Run tests
        run: mvn test

      # 6. OWASP Dependency Check
      - name: OWASP Dependency Check
        run: mvn org.owasp:dependency-check-maven:check

      # 7. Docker build
      - name: Build Docker image
        run: docker build -t student-crud-app .

      # 8. Scan Docker image with Trivy
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: student-crud-app

      # 9. Optional: Push Docker image to Docker Hub
      # Make sure to set DOCKER_USERNAME and DOCKER_PASSWORD as GitHub secrets
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag student-crud-app ${{ secrets.DOCKER_USERNAME }}/student-crud-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/student-crud-app:latest
