name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    env:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/demo_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    - name: Build Maven project
      run: mvn clean package

    - name: Run Tests
      run: mvn test

    # ----------------------
    # OWASP Dependency Check
    - name: Run OWASP Dependency-Check
      uses: jeremylong/owasp-dependency-check-action@v2
      with:
        scan: './'
        format: 'HTML'
        out: 'reports/owasp'

    # ----------------------
    # Docker Build
    - name: Build Docker Image
      run: docker build -t spring_app:latest .

    # ----------------------
    # Trivy Scan
    - name: Scan Docker Image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: spring_app:latest
        format: 'table'
        exit-code: '1'
        severity: 'CRITICAL,HIGH'
        output: reports/trivy-report.txt

    # ----------------------
    # Email Reports
    - name: Send Reports via Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "DevSecOps Reports - Demo Project"
        body: "Attached are OWASP and Trivy reports."
        to: takwa.laffet@esprit.tn
        attachments: reports/owasp/dependency-check-report.html,reports/trivy-report.txt